### ISSUE TITLE
cannot able to get obfuscated code

### ISSUE THREAD

**Issue by poojab** [Polidea/SiriusObfuscator#29]
Getting below error:

1) File Extractor:
⡀⡀⡀⠄⠂⠁⠂⠄⡀⢀⠠⠐⠈⠁⠂⠄Extracting⡀⡀⡀⠄⠂⠁⠂⠄⡀⢀⠠⠐⠈⠁⠂⠄
STDERR: /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/ruby/lib/ruby/2.2.0/rexml/source.rb:17:in `require': cannot load such file -- stringio (LoadError)
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/ruby/lib/ruby/2.2.0/rexml/source.rb:17:in `create_from'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/ruby/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:128:in `stream='
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/ruby/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:117:in `initialize'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/ruby/lib/ruby/2.2.0/rexml/parsers/treeparser.rb:9:in `new'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/ruby/lib/ruby/2.2.0/rexml/parsers/treeparser.rb:9:in `initialize'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/ruby/lib/ruby/2.2.0/rexml/document.rb:287:in `new'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/ruby/lib/ruby/2.2.0/rexml/document.rb:287:in `build'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/ruby/lib/ruby/2.2.0/rexml/document.rb:44:in `initialize'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/vendor/ruby/2.2.0/gems/xcodeproj-1.5.3/lib/xcodeproj/workspace.rb:83:in `new'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/vendor/ruby/2.2.0/gems/xcodeproj-1.5.3/lib/xcodeproj/workspace.rb:83:in `from_s'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/vendor/ruby/2.2.0/gems/xcodeproj-1.5.3/lib/xcodeproj/workspace.rb:66:in `new_from_xcworkspace'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/file-extractor/lib/file-extractor/xcworkspace_extractor.rb:19:in `extract_projects_and_dependency_schemes'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/file-extractor/lib/file-extractor/command.rb:96:in `run'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/vendor/ruby/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/file-extractor/lib/file-extractor/command.rb:76:in `run'
	from /Users/poojab/Downloads/Obfuscator_2018-04-24_115109/bin/lib/file-extractor/bin/file-extractor:20:in `<main>'
STDOUT: 

===========================

2) Symbol Extractor:
⠁⠂⠄⡀⢀⠠⠐⠈⠁⠂⠄⡀⢀⠠⠐⠈Extracting⠁⠂⠄⡀⢀⠠⠐⠈⠁⠂⠄⡀⢀⠠⠐⠈
STDERR: Error during JSON file read
STDOUT: Swift obfuscator symbol extractor tool

**Comment by sizaan5** [comment]
I am facing the same problem, any update on this issue?
